// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Test.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__TEST_HPP
#define FAST_DDS_GENERATED__TEST_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TEST_SOURCE)
#define TEST_DllAPI __declspec( dllexport )
#else
#define TEST_DllAPI __declspec( dllimport )
#endif // TEST_SOURCE
#else
#define TEST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TEST_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure Test defined by the user in the IDL file.
 * @ingroup Test
 */
class Test
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Test()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Test()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Test that will be copied.
     */
    eProsima_user_DllExport Test(
            const Test& x)
    {
                    m_msg = x.m_msg;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Test that will be copied.
     */
    eProsima_user_DllExport Test(
            Test&& x) noexcept
    {
        m_msg = std::move(x.m_msg);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Test that will be copied.
     */
    eProsima_user_DllExport Test& operator =(
            const Test& x)
    {

                    m_msg = x.m_msg;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Test that will be copied.
     */
    eProsima_user_DllExport Test& operator =(
            Test&& x) noexcept
    {

        m_msg = std::move(x.m_msg);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Test object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Test& x) const
    {
        return (m_msg == x.m_msg);
    }

    /*!
     * @brief Comparison operator.
     * @param x Test object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Test& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member msg
     * @param _msg New value to be copied in member msg
     */
    eProsima_user_DllExport void msg(
            const std::string& _msg)
    {
        m_msg = _msg;
    }

    /*!
     * @brief This function moves the value in member msg
     * @param _msg New value to be moved in member msg
     */
    eProsima_user_DllExport void msg(
            std::string&& _msg)
    {
        m_msg = std::move(_msg);
    }

    /*!
     * @brief This function returns a constant reference to member msg
     * @return Constant reference to member msg
     */
    eProsima_user_DllExport const std::string& msg() const
    {
        return m_msg;
    }

    /*!
     * @brief This function returns a reference to member msg
     * @return Reference to member msg
     */
    eProsima_user_DllExport std::string& msg()
    {
        return m_msg;
    }



private:

    std::string m_msg;

};

#endif // _FAST_DDS_GENERATED_TEST_HPP_


